# Generated by Django 3.2.25 on 2024-08-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20240727_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_confession',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz_date',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='quiz_invite',
            name='explanation',
            field=models.TextField(null=True),
        ),
    ]
